### ISSUE TITLE
[Bug] Spark engine can not exit when enable authz plugin

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4270]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

It was reported by some users that when using the Spark Ranger plugin (Kyuubi authz module) w/ Kyuubi, the Driver JVM process can not exit even after `SparkSQLEngine` and `SparkContext` was stopped.

After some investigation by `jstack`, I found the JVM hang because of some non-daemon threads opened by Ranger Audit plugins, i.e. ES, Solr

See [RANGER-3787](https://issues.apache.org/jira/browse/RANGER-3787) for details about issue related to ES audit plugin 

### Affects Version(s)

master/1.6

### Kyuubi Engine Log Output

As you can see, the `SparkSQLEngine` and `SparkContext` was stopped, but the JVM process is still alive.

```logtalk
23/02/08 03:45:03 INFO EngineServiceDiscovery: Clean up discovery service due to this is connection share level.
23/02/08 03:45:03 INFO EngineServiceDiscovery: Service[EngineServiceDiscovery] is stopped.
23/02/08 03:45:03 INFO SparkTBinaryFrontendService: Service[SparkTBinaryFrontend] is stopped.
23/02/08 03:45:03 INFO SparkTBinaryFrontendService: SparkTBinaryFrontend has stopped
23/02/08 03:45:03 INFO SparkSQLEngine: Service: [SparkSQLBackendService] is stopping.
23/02/08 03:45:03 INFO SparkSQLBackendService: Service: [SparkSQLSessionManager] is stopping.
23/02/08 03:45:03 INFO SparkSQLSessionManager: Service: [SparkSQLOperationManager] is stopping.
23/02/08 03:45:03 INFO SparkSQLOperationManager: Service[SparkSQLOperationManager] is stopped.
23/02/08 03:45:03 INFO SparkSQLSessionManager: Service[SparkSQLSessionManager] is stopped.
23/02/08 03:45:03 INFO SparkSQLBackendService: Service[SparkSQLBackendService] is stopped.
23/02/08 03:45:03 INFO SparkSQLEngine: Service[SparkSQLEngine] is stopped.
23/02/08 03:45:03 INFO SparkTBinaryFrontendService: Finished closing SessionHandle [a1176c3c-e2a4-497c-b0fe-af6907017284]
23/02/08 03:45:03 INFO SparkUI: Stopped Spark web UI at http://spark-8bca9c862f1fda07-driver-svc.spark.svc:4040
23/02/08 03:45:03 INFO KubernetesClusterSchedulerBackend: Shutting down all executors
23/02/08 03:45:03 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Asking each executor to shut down
23/02/08 03:45:03 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed.
23/02/08 03:45:04 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
23/02/08 03:45:04 INFO MemoryStore: MemoryStore cleared
23/02/08 03:45:04 INFO BlockManager: BlockManager stopped
23/02/08 03:45:04 INFO BlockManagerMaster: BlockManagerMaster stopped
23/02/08 03:45:04 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
23/02/08 03:45:04 INFO SparkContext: Successfully stopped SparkContext
23/02/08 03:45:53 INFO BaseAuditHandler: Audit Status Log: name=sparkSql.async.batch, finalDestination=sparkSql.async.batch.solr, interval=01:00.008 minutes, events=4, succcessCount=2, totalEvents=4, totalSuccessCount=2
```

### Additional context

The ranger audit configuration
```
    <property>
      <name>xasecure.audit.is.enabled</name>
      <value>true</value>
    </property>
    <property>
      <name>xasecure.audit.destination.solr</name>
      <value>true</value>
    </property>
    <property>
      <name>xasecure.audit.destination.solr.batch.filespool.dir</name>
      <value>/var/log/spark/audit/solr/spool</value>
    </property>
    <property>
      <name>xasecure.audit.destination.solr.zookeepers</name>
      <value>192.168.1.80:2181/infra-solr</value>
    </property>
    <property>
      <name>xasecure.audit.destination.solr.urls</name>
      <value>NONE</value>
    </property>
    <property>
      <name>xasecure.audit.destination.solr.user</name>
      <value>ranger_solr</value>
    </property>
    <property>
      <name>xasecure.audit.destination.solr.password</name>
      <value>[REDECTED]</value>
    </property>
```
The stucked Driver JVM jstack output
```
"zkConnectionManagerCallback-5-thread-1" #134 prio=5 os_prio=0 tid=0x00007f2c90008800 nid=0x108b waiting on condition [0x00007f2ca98e8000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000fae5b628> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None
```
The `zkConnectionManagerCallback-*` is actually created by Solr Zk client

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
cc @bowenliang123 @zhouyifan279

**Comment by bowenliang123** [comment]
Let's register a shutdown hook with `org.apache.spark.util.ShutdownHookManage` to properly cleanup the plugin by calling `RangerBasePlugin.cleanup()`.

Among plugins provided in Ranger, plugins for kafka、hbase、solr does manually clean up but the one for hive doesn't.

**Comment by user-GitHub-user** [comment]
hi, I had the same problem in 1.7.0, any suggestions?

```
23/12/21 09:37:01 ERROR SparkSQLEngine: RECEIVED SIGNAL 15: TERM
23/12/21 09:37:01 ERROR ApplicationMaster: RECEIVED SIGNAL TERM
23/12/21 09:37:01 INFO SparkRangerAdminPlugin$: clean up ranger plugin, appId: sparkSql
23/12/21 09:37:01 INFO PolicyRefresher: PolicyRefresher(serviceName=metastore).run(): interrupted! Exiting thread
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ranger.plugin.util.PolicyRefresher.run(PolicyRefresher.java:160)
23/12/21 09:37:01 INFO SparkSQLEngine: Service: [SparkTBinaryFrontend] is stopping.
23/12/21 09:37:01 INFO SparkTBinaryFrontendService: Service: [EngineServiceDiscovery] is stopping.
23/12/21 09:37:01 WARN ZookeeperDiscoveryClient: This Kyuubi instance cqdev01:41229 is now de-registered from ZooKeeper. The server will be shut down after the last client session completes.
23/12/21 09:37:01 INFO EngineServiceDiscovery: 2 connection(s) are active, delay shutdown
23/12/21 09:37:01 INFO CuratorFrameworkImpl: backgroundOperationsLoop exiting
23/12/21 09:37:01 INFO ZooKeeper: Session: 0x200000ea4be5384 closed
23/12/21 09:37:01 INFO EngineServiceDiscovery: Service[EngineServiceDiscovery] is stopped.
23/12/21 09:37:01 INFO SparkTBinaryFrontendService: Service[SparkTBinaryFrontend] is stopped.
23/12/21 09:37:01 INFO SparkTBinaryFrontendService: SparkTBinaryFrontend has stopped
23/12/21 09:37:01 INFO SparkSQLEngine: Service: [SparkSQLBackendService] is stopping.
23/12/21 09:37:01 INFO SparkSQLBackendService: Service: [SparkSQLSessionManager] is stopping.
23/12/21 09:37:01 INFO SparkSQLSessionManager: Service: [SparkSQLOperationManager] is stopping.
23/12/21 09:37:01 INFO SparkSQLOperationManager: Service[SparkSQLOperationManager] is stopped.
23/12/21 09:37:01 INFO SparkSQLSessionManager: Service[SparkSQLSessionManager] is stopped.
23/12/21 09:37:01 INFO SparkSQLBackendService: Service[SparkSQLBackendService] is stopped.
23/12/21 09:37:01 INFO SparkSQLEngine: Service[SparkSQLEngine] is stopped.
23/12/21 09:37:01 INFO ApplicationMaster: Final app status: FAILED, exitCode: 16, (reason: Shutdown hook called before final status was reported.)
23/12/21 09:37:01 INFO DiskBlockManager: Shutdown hook called
23/12/21 09:37:01 INFO ShutdownHookManager: Shutdown hook called
23/12/21 09:37:01 INFO ShutdownHookManager: Deleting directory /data/module/hadoop-3.1.4/yarn/local/usercache/hadoop/appcache/application_1699966942074_0696/spark-1fe5ccf6-89f6-474c-ba42-5b49dc6e206f
23/12/21 09:37:01 INFO ShutdownHookManager: Deleting directory /data/module/hadoop-3.1.4/yarn/local/usercache/hadoop/appcache/application_1699966942074_0696/spark-1fe5ccf6-89f6-474c-ba42-5b49dc6e206f/userFiles-35f8d57d-613f-460b-ae6f-31ccd380fa7d
23/12/21 09:37:01 INFO AuditProviderFactory: ==> JVMShutdownHook.run()
23/12/21 09:37:01 INFO AuditProviderFactory: JVMShutdownHook: Signalling async audit cleanup to start.
23/12/21 09:37:01 INFO AuditProviderFactory: RangerAsyncAuditCleanup: Starting cleanup
23/12/21 09:37:01 INFO AuditProviderFactory: JVMShutdownHook: Waiting up to 30 seconds for audit cleanup to finish.
23/12/21 09:37:01 INFO AuditAsyncQueue: Stop called. name=sparkSql.async
23/12/21 09:37:01 INFO AuditAsyncQueue: Interrupting consumerThread. name=sparkSql.async, consumer=sparkSql.async.batch
23/12/21 09:37:01 INFO AuditProviderFactory: RangerAsyncAuditCleanup: Done cleanup
23/12/21 09:37:01 INFO AuditProviderFactory: RangerAsyncAuditCleanup: Waiting to audit cleanup start signal
23/12/21 09:37:01 INFO AuditProviderFactory: JVMShutdownHook: Audit cleanup finished after 0 milli seconds
23/12/21 09:37:01 INFO AuditProviderFactory: JVMShutdownHook: Interrupting ranger async audit cleanup thread
23/12/21 09:37:01 INFO AuditProviderFactory: <== JVMShutdownHook.run()
23/12/21 09:37:01 INFO AuditProviderFactory: RangerAsyncAuditCleanup: Interrupted while waiting for audit startCleanup signal!  Exiting the thread...
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at org.apache.ranger.audit.provider.AuditProviderFactory$RangerAsyncAuditCleanup.run(AuditProviderFactory.java:495)
	at java.lang.Thread.run(Thread.java:748)
23/12/21 09:37:01 INFO AuditAsyncQueue: Caught exception in consumer thread. Shutdown might be in progress
23/12/21 09:37:01 INFO AuditAsyncQueue: Exiting polling loop. name=sparkSql.async
23/12/21 09:37:01 INFO AuditAsyncQueue: Calling to stop consumer. name=sparkSql.async, consumer.name=sparkSql.async.batch
23/12/21 09:37:01 INFO AuditBatchQueue: Stop called. name=sparkSql.async.batch
23/12/21 09:37:01 INFO AuditBatchQueue: Interrupting consumerThread. name=sparkSql.async.batch, consumer=sparkSql.async.batch.log4j
23/12/21 09:37:01 INFO AuditAsyncQueue: Exiting consumerThread.run() method. name=sparkSql.async
23/12/21 09:37:01 INFO AuditBatchQueue: Caught exception in consumer thread. Shutdown might be in progress
23/12/21 09:37:01 INFO AuditBatchQueue: Exiting consumerThread. Queue=sparkSql.async.batch, dest=sparkSql.async.batch.log4j
23/12/21 09:37:01 INFO AuditBatchQueue: Calling to stop consumer. name=sparkSql.async.batch, consumer.name=sparkSql.async.batch.log4j
23/12/21 09:37:01 INFO BaseAuditHandler: Audit Status Log: name=sparkSql.async.batch.log4j, interval=01:05.757 minutes, events=108, succcessCount=108, totalEvents=154, totalSuccessCount=154
23/12/21 09:37:01 INFO BaseAuditHandler: Audit Status Log: name=sparkSql.async.batch, finalDestination=sparkSql.async.batch.log4j, interval=29.756 seconds, events=5, succcessCount=2, totalEvents=2806, totalSuccessCount=154
23/12/21 09:37:01 INFO AuditBatchQueue: Exiting consumerThread.run() method. name=sparkSql.async.batch
23/12/21 09:37:01 INFO SparkUI: Stopped Spark web UI at http://cqdev01:32833
23/12/21 09:37:01 INFO YarnClusterSchedulerBackend: Shutting down all executors
23/12/21 09:37:01 INFO YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
```
