### ISSUE TITLE
[Bug] kyuubi-hive-jdbc-shaded should not contains slf4j package

### ISSUE THREAD

**Issue by zyclove** [apache/kyuubi#4659]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

<dependency>
    <groupId>org.apache.kyuubi</groupId>
    <artifactId>kyuubi-hive-jdbc-shaded</artifactId>
    <version>1.7.0</version>
</dependency>

it contains slf4j, but conflicts with slf4j.
![image](https://user-images.githubusercontent.com/15028279/229679835-9bd7f9d3-8d34-4723-8065-5a89c6306ff3.png)
![image](https://user-images.githubusercontent.com/15028279/229680230-7eb4ccbb-5032-4d51-98a2-b58fff3b4e98.png)

Could you solve and upgrade it as soon as possible, thank you.

Best regards

### Affects Version(s)

1.7.0

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
This is kinda relocation leak, but I suppose slf4j 1.7.36 should be compatible w/ 1.7.35, could you provide more stacktrace (please use text instead of picture)?

**Comment by zyclove** [comment]
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.alipay.sofa.ark.support.startup.EmbedSofaArkBootstrap.deployStaticBizAfterEmbedMasterBizStarted(EmbedSofaArkBootstrap.java:103)
	... 17 common frames omitted
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader com.alipay.sofa.ark.container.service.classloader.BizClassLoader @67c2ff5d of the current class, org/slf4j/LoggerFactory, and the class loader 'app' for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader com.alipay.sofa.ark.container.service.classloader.BizClassLoader @67c2ff5d, parent loader 'bootstrap'; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'app')
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:61)
	at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
	at com.alipay.sofa.ark.container.pipeline.DeployBizStage.processStaticBiz(DeployBizStage.java:56)
	at com.alipay.sofa.ark.container.ArkContainer.deployBizAfterMasterBizReady(ArkContainer.java:168)
	... 22 common frames omitted
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader com.alipay.sofa.ark.container.service.classloader.BizClassLoader @67c2ff5d of the current class, org/slf4j/LoggerFactory, and the class loader 'app' for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader com.alipay.sofa.ark.container.service.classloader.BizClassLoader @67c2ff5d, parent loader 'bootstrap'; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'app')
	**at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)**

Just for , kyuubi-hive-jdbc-shaded inner has  org.slf4j package, as follows.
![image](https://user-images.githubusercontent.com/15028279/229682189-b5f262e3-db68-466e-bdb8-c3e3fdc2edef.png)

I will try upgrade  slf4j  to 1.7.36, but i think do not work too. Thanks .

**Comment by zyclove** [comment]
![image](https://user-images.githubusercontent.com/15028279/229683571-5da976d4-405c-4448-bcf7-462e38e3959e.png)
As expected it doesn't work.
Why does kyuubi-hive-jdbc-shaded include slf4j dependencies internally?
![image](https://user-images.githubusercontent.com/15028279/229683835-fd967b71-7df0-4a0d-ac69-ba270908331f.png)
![image](https://user-images.githubusercontent.com/15028279/229683947-23298e82-cde4-4491-9275-d6ba92a0fd4e.png)
Is it because no one else is using.

**Comment by pan3793** [comment]
As a workaround, you can use the vanilla driver instead `kyuubi-hive-jdbc`

**Comment by okue** [comment]
+1
