### ISSUE TITLE
[Bug] Caused by: java.net.UnknownHostException: kyuubi-bd8f56ddb-59jn5

### ISSUE THREAD

**Issue by weijiasheng** [apache/kyuubi#5040]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [x] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

hello, I want to run a beeline， 
```
/opt/spark-3.2.2-bin-custom-spark/bin/beeline -u "jdbc:hive2://vm23:32121/"  -n ***
```
but spark exector can not conntect to driver：
```
+ exec /usr/bin/tini -s -- /usr/local/openjdk-11/bin/java -Dspark.driver.port=34030 -Xms1024m -Xmx1024m -cp '/opt/spark/conf::/opt/spark/jars/*:' org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@kyuubi-bd8f56ddb-59jn5:34030 --executor-id 6 --cores 1 --app-id spark-application-1688714736039 --hostname 10.244.125.214 --resourceProfileId 0

Caused by: java.net.UnknownHostException: kyuubi-bd8f56ddb-59jn5
```

### Affects Version(s)

1.7.1

### Kyuubi Server Log Output
```
3/07/07 07:28:33 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed.
23/07/07 07:28:33 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
23/07/07 07:28:33 INFO MemoryStore: MemoryStore cleared
23/07/07 07:28:33 INFO BlockManager: BlockManager stopped
23/07/07 07:28:33 INFO BlockManagerMaster: BlockManagerMaster stopped
23/07/07 07:28:33 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
23/07/07 07:28:33 INFO SparkContext: Successfully stopped SparkContext
23/07/07 07:28:33 INFO ShutdownHookManager: Shutdown hook called
23/07/07 07:28:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-19ee14fa-c91b-4fbe-a5d3-3008cd384459
23/07/07 07:28:33 INFO ShutdownHookManager: Deleting directory /tmp/local-dir/spark-8e381bd9-782f-4ca4-80de-9f15a66bccb0
at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.engine.ProcBuilder.getError(ProcBuilder.scala:271) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.engine.ProcBuilder.getError$(ProcBuilder.scala:264) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.engine.spark.SparkProcessBuilder.getError(SparkProcessBuilder.scala:37) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.engine.EngineRef.$anonfun$create$6(EngineRef.scala:235) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.engine.EngineRef.$anonfun$create$6$adapted(EngineRef.scala:224) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at scala.Option.foreach(Option.scala:407) ~[scala-library-2.12.17.jar:?]
at org.apache.kyuubi.engine.EngineRef.$anonfun$create$5(EngineRef.scala:224) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.engine.EngineRef.$anonfun$create$5$adapted(EngineRef.scala:220) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at scala.Option.foreach(Option.scala:407) ~[scala-library-2.12.17.jar:?]
at org.apache.kyuubi.engine.EngineRef.$anonfun$create$1(EngineRef.scala:220) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.ha.client.zookeeper.ZookeeperDiscoveryClient.tryWithLock(ZookeeperDiscoveryClient.scala:180) ~[kyuubi-ha_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.engine.EngineRef.tryWithLock(EngineRef.scala:168) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.engine.EngineRef.create(EngineRef.scala:173) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.engine.EngineRef.$anonfun$getOrCreate$1(EngineRef.scala:271) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at scala.Option.getOrElse(Option.scala:189) ~[scala-library-2.12.17.jar:?]
at org.apache.kyuubi.engine.EngineRef.getOrCreate(EngineRef.scala:271) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$2(KyuubiSessionImpl.scala:147) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$2$adapted(KyuubiSessionImpl.scala:123) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.ha.client.DiscoveryClientProvider$.withDiscoveryClient(DiscoveryClientProvider.scala:36) ~[kyuubi-ha_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:123) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.session.KyuubiSession.handleSessionException(KyuubiSession.scala:49) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:123) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$2(LaunchEngine.scala:60) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
... 3 more
2023-07-07 08:22:12.730 INFO org.apache.kyuubi.server.KyuubiTBinaryFrontendService: Received request of closing SessionHandle [d243111e-9065-4f2c-9d71-622e22ad1cb5]
2023-07-07 08:22:12.743 INFO org.apache.kyuubi.session.KyuubiSessionManager: wjs's session with SessionHandle [d243111e-9065-4f2c-9d71-622e22ad1cb5] is closed, current opening sessions 0
```
### Kyuubi Engine Log Output
```
23/07/07 08:22:26 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(kyuubi, spark_operator); groups with view permissions: Set(); users with modify permissions: Set(kyuubi, spark_operator); groups with modify permissions: Set()
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1780)
at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:419)
at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:408)
at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$9(CoarseGrainedExecutorBackend.scala:439)
at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
at scala.collection.immutable.Range.foreach(Range.scala:158)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$7(CoarseGrainedExecutorBackend.scala:437)
at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62)
at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/javax.security.auth.Subject.doAs(Unknown Source)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
... 4 more
Caused by: java.io.IOException: Failed to connect to kyuubi-bd8f56ddb-59jn5:38519
at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: kyuubi-bd8f56ddb-59jn5
at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source)
at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
at java.base/java.net.InetAddress.getAllByName(Unknown Source)
at java.base/java.net.InetAddress.getAllByName(Unknown Source)
at java.base/java.net.InetAddress.getByName(Unknown Source)
at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
... 1 more
```

### Kyuubi Server Configurations
```
## Helm chart provided Kyuubi configurations
kyuubi.kubernetes.namespace=kyuubi
kyuubi.frontend.connection.url.use.hostname=false
kyuubi.frontend.thrift.binary.bind.port=10009
kyuubi.frontend.thrift.http.bind.port=10010
kyuubi.frontend.rest.bind.port=10099
kyuubi.frontend.mysql.bind.port=3309
kyuubi.frontend.protocols=REST,THRIFT_BINARY

## User provided Kyuubi configurations
spark.kubernetes.container.image=kyuubi:v1.7.1
spark.kubernetes.namespace=kyuubi
```

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
The information you provided is scattered and the chances of getting a detailed answer are low.

**Comment by weijiasheng** [comment]
> The information you provided is scattered and the chances of getting a detailed answer are low.

I had update it,thanks

**Comment by pan3793** [comment]
Some of the information is not accurate, but it shows patience at least, some of the following analyses are based on my guessing.

> beeline -u "jdbc:hive2://vm23:32121/"

What is the `vm23:32121`, where is your Kyuubi Server running? It looks like a virtual machine address, but you claim deploying Kyuubi on K8s.

> `... --app-id spark-application-1688714736039 ...`

This Application ID pattern is not Spark on K8s, it should be like `spark-bd4729b7dc6c4fa99e2482b3ee4a6598` instead

```
+ exec /usr/bin/tini -s -- /usr/local/openjdk-11/bin/java -Dspark.driver.port=34030 -Xms1024m -Xmx1024m -cp '/opt/spark/conf::/opt/spark/jars/*:' org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@kyuubi-bd8f56ddb-59jn5:34030 --executor-id 6 --cores 1 --app-id spark-application-1688714736039 --hostname 10.244.125.214 --resourceProfileId 0

Caused by: java.net.UnknownHostException: kyuubi-bd8f56ddb-59jn5
```

so your driver is running at `kyuubi-bd8f56ddb-59jn5` and one of your executors is running at `10.244.125.214`, and the latter can not access the former, it's a network issue related to DNS. what's the network topology of your setup?

> Kyuubi Server Log Output
> ```
> 23/07/07 07:28:33 INFO ...
> 
> 2023-07-07 08:22:12.730 INFO ...
> ```

Is all content from one output? the timestamp pattern is different.

> Kyuubi Engine Log Output

This should be the Spark driver's log, but your provided looks like a Spark executor's log.

> `spark.kubernetes.container.image=kyuubi:v1.7.1`

This should point to a Spark image, not Kyuubi image. 

Kyuubi is not a wrapper of Spark, it is another service that can leverage your existing computing engine setup, if you choose Spark on K8s as your Kyuubi engine, it supposes you have basic knowledge of Spark and Kubernetes.

https://spark.apache.org/docs/latest/running-on-kubernetes.html

**Comment by pan3793** [comment]
Close as no further response from the reporter for a long time.
