### ISSUE TITLE
[Bug] [AUTHZ] Spark crashes with ClassCastException when resolving a join of masked tables

### ISSUE THREAD

**Issue by pilietis93** [apache/kyuubi#5092]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Hi, we're using your `spark-authz` lib which started crashing for some workflows after upgrading 1.6.1 -> 1.7.1
This only happens when joining a table that contains masked columns even though they're not used in the join condition. 

```
Exception in thread "main" java.lang.ClassCastException: class org.apache.kyuubi.plugin.spark.authz.ranger.datamasking.DataMaskingStage1Marker cannot be cast to class org.apache.spark.sql.catalyst.plans.logical.Join (org.apache.kyuubi.plugin.spark.authz.ranger.datamasking.DataMaskingStage1Marker and org.apache.spark.sql.catalyst.plans.logical.Join are in unnamed module of loader 'app')
 	at org.apache.spark.sql.Dataset.resolveSelfJoinCondition(Dataset.scala:1069)
 	at org.apache.spark.sql.Dataset.join(Dataset.scala:1117)
       [..] our code
```

This should be enough to reproduce it:
```
val df0 = sqlContext.table("table_with_masked_col") // only col2 is masked which is not used
      .select($"col0", $"col1")

    df0.as("a")
      .join(
        right = df0.as("b"),
        joinExprs = $"a.col0" === $"b.col0" && $"a.col1" === $"b.col1",
        joinType = "left_outer") // crashes
```

We had to downgrade to 1.6.1 where this doesn't happen.

### Affects Version(s)

1.7.1

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by yaooqinn** [comment]
I understand the issue. thanks for reporting this

**Comment by xza-m** [comment]
@pilietis93 Hello, can you full in some information about this bug , so I can reproduce it. Such as your spark-version and mark rule.

**Comment by pilietis93** [comment]
@xza-m we use Spark 3.3.2, `col2` is masked with "nullify" option via a tag based policy. Let me know if you need further info.
