### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ymZhao1001** [apache/kyuubi#5262]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

while using the hive engine,  the remote hive version is 2.3.9 ;
bin/beeline -u 'jdbc:hive2://10.0.30.14:10009/default?kyuubi.engine.type=HIVE_SQL' -n hive

error:
![image](https://github.com/apache/kyuubi/assets/19317643/876f12f8-2531-4fd9-bd2d-fd8720ced947)

### Affects Version(s)

1.7.0

### Kyuubi Engine Log Output

```logtalk
2023-09-07 11:34:17.538 ERROR org.apache.kyuubi.metrics.JsonReporterService: Error writing metrics to json file: /home/databig/apache-kyuubi-1.7.1-bin/work/metrics/report.json
java.nio.file.NoSuchFileException: /home/databig/apache-kyuubi-1.7.1-bin/work/metrics/report8146670077417272879.json
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_351]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_351]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_351]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_351]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_351]
        at java.nio.file.Files.createFile(Files.java:632) ~[?:1.8.0_351]
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:138) ~[?:1.8.0_351]
        at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161) ~[?:1.8.0_351]
        at java.nio.file.Files.createTempFile(Files.java:852) ~[?:1.8.0_351]
        at org.apache.kyuubi.metrics.JsonReporterService$$anon$1.run(JsonReporterService.scala:61) ~[kyuubi-metrics_2.12-1.7.1.jar:1.7.1]
        at java.util.TimerThread.mainLoop(Timer.java:555) ~[?:1.8.0_351]
        at java.util.TimerThread.run(Timer.java:505) ~[?:1.8.0_351]
```

### Kyuubi Server Configurations

```yaml
export JAVA_HOME=/usr/local/jdk1.8.0_351
export HIVE_HOME=/home/databig/apache-hive-3.1.3-bin
export HADOOP_CONF_DIR=/home/databig/hadoop-3.3.4/etc/hadoop
export HADOOP_HOME=/home/databig/hadoop-3.3.4
export HIVE_HADOOP_CLASSPATH=`${HADOOP_HOME}/bin/hadoop classpath`
```

### Kyuubi Engine Configurations

```yaml
hive.metastore.uris thrift://10.0.30.14:9083
kyuubi.engine.hive.java.options -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
```

### Additional context

remote hive version is 2.3.9

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
The current Hive engine implementation is verified with Apache Hive 3.1.3, extra efforts may be required for adapting other Hive versions, like Apache Hive 2.3, 4.0, or vendor-specific versions like Hive 2.1.1-cdh-6.x.

BTW, please provide the error logs in text instead of the picture, the latter is not searchable.

**Comment by ymZhao1001** [comment]
2023-09-13T09:17:23,747 ERROR [HiveTBinaryFrontendHandler-Pool: Thread-37] org.apache.kyuubi.engine.hive.HiveTBinaryFrontendService - Error opening session: 
org.apache.kyuubi.KyuubiSQLException: Database default does not exist
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69) ~[kyuubi-hive-sql-engine_2.12-1.7.2-SNAPSHOT.jar:1.7.2-SNAPSHOT]
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:73) ~[kyuubi-hive-sql-engine_2.12-1.7.2-SNAPSHOT.jar:1.7.2-SNAPSHOT]
        at org.apache.kyuubi.session.SessionManager.openSession(SessionManager.scala:119) ~[kyuubi-hive-sql-engine_2.12-1.7.2-SNAPSHOT.jar:1.7.2-SNAPSHOT]
        at org.apache.kyuubi.service.AbstractBackendService.openSession(AbstractBackendService.scala:45) ~[kyuubi-hive-sql-engine_2.12-1.7.2-SNAPSHOT.jar:1.7.2-SNAPSHOT]
        at org.apache.kyuubi.service.TFrontendService.getSessionHandle(TFrontendService.scala:181) ~[kyuubi-hive-sql-engine_2.12-1.7.2-SNAPSHOT.jar:1.7.2-SNAPSHOT]
        at org.apache.kyuubi.service.TFrontendService.OpenSession(TFrontendService.scala:190) [kyuubi-hive-sql-engine_2.12-1.7.2-SNAPSHOT.jar:1.7.2-SNAPSHOT]
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1497) [hive-service-rpc-3.1.3.jar:3.1.3]
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1482) [hive-service-rpc-3.1.3.jar:3.1.3]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36) [kyuubi-hive-sql-engine_2.12-1.7.2-SNAPSHOT.jar:1.7.2-SNAPSHOT]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [libthrift-0.9.3.jar:0.9.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_351]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_351]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]
Caused by: org.apache.hive.service.cli.HiveSQLException: Database default does not exist
        at org.apache.hive.service.cli.session.HiveSessionImpl.configureSession(HiveSessionImpl.java:294) ~[hive-service-3.1.3.jar:3.1.3]
        at org.apache.hive.service.cli.session.HiveSessionImpl.open(HiveSessionImpl.java:199) ~[hive-service-3.1.3.jar:3.1.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_351]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_351]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_351]
        at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:78) ~[hive-service-3.1.3.jar:3.1.3]
        at org.apache.hive.service.cli.session.HiveSessionProxy.access$000(HiveSessionProxy.java:36) ~[hive-service-3.1.3.jar:3.1.3]
        at org.apache.hive.service.cli.session.HiveSessionProxy$1.run(HiveSessionProxy.java:63) ~[hive-service-3.1.3.jar:3.1.3]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_351]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_351]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:59) ~[hive-service-3.1.3.jar:3.1.3]
        at com.sun.proxy.$Proxy21.open(Unknown Source) ~[?:?]
        at org.apache.kyuubi.engine.hive.session.HiveSessionImpl.open(HiveSessionImpl.scala:50) ~[kyuubi-hive-sql-engine_2.12-1.7.2-SNAPSHOT.jar:1.7.2-SNAPSHOT]
        at org.apache.kyuubi.session.SessionManager.openSession(SessionManager.scala:107) ~[kyuubi-hive-sql-engine_2.12-1.7.2-SNAPSHOT.jar:1.7.2-SNAPSHOT]
        ... 12 more

**Comment by ymZhao1001** [comment]
@pan3793 hello,can u help to take a look？

**Comment by ymZhao1001** [comment]
![image](https://github.com/apache/kyuubi/assets/19317643/68245fe9-fa43-4d61-b444-118b0cda05e4)
![image](https://github.com/apache/kyuubi/assets/19317643/06534608-d6ea-4125-8178-3911133167f3)

**Comment by pan3793** [comment]
Sounds like Hive Server 3.1 is not compatible with Hive Metastore Service 2.3?

**Comment by pan3793** [comment]
One goal of the Kyuubi engine is to compatible with different engine runtimes.

For example, the Kyuubi Spark engine built against Spark 3.4 is compatible with Spark 3.1 ~ 3.4 runtime.

For Kyuubi Hive engine, we currently build against Hive 3.1, and only test with Hive 3.1 runtime, have you tested setting `HVIE_HOME` in `kyuubi-env.sh` to point Hive 2.3.9 and see what happens?

**Comment by ymZhao1001** [comment]
> One goal of the Kyuubi engine is to compatible with different versions of engine runtime.
> 
> For example, the Kyuubi Spark engine built against Spark 3.4 is compatible with Spark 3.1 ~ 3.4 runtime.
> 
> For Kyuubi Hive engine, we currently build against Hive 3.1, and only test with Hive 3.1 runtime, have you tested setting `HVIE_HOME` in `kyuubi-env.sh` to point Hive 2.3.9 and see what happens? I think we can make the Hive engine support Hive 2.3.9 or even Hive 2.1.1-cdh6.x since they are the most adopted versions.

java.lang.NoSuchMethodError: org.apache.hive.service.cli.session.HiveSessionImplwithUGI.<init>(Lorg/apache/hive/service/cli/SessionHandle;Lorg/apache/hive/service/rpc/thrift/TProtocolVersion;Ljava/lang/String;Ljava/lang/String;Lorg/apache/hadoop/hive/conf/HiveConf;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)V


and then i change the method to 2.3.9,rebuild the hive-sql-engine
then another error
TProtocolException: Missing version in readMessageBegin, old client?

**Comment by pan3793** [comment]
> TProtocolException: Missing version in readMessageBegin, old client?

generally, it's caused by client version < server version

**Comment by ymZhao1001** [comment]
i  use beeline in hive 2.3.9 to connect hive3.1.3 hiveserver2 ,it will be ok.  what can i do in kyuubi? @pan3793

**Comment by pan3793** [comment]
@ymZhao1001 I have a quick draft patch to make the Hive engine compatible with Hive 2.3.9 https://github.com/apache/kyuubi/pull/5280.

Note, the PR is work-in-progess, and has not passed all UTs. I'm quite busy with other stuff these days. In my local test, the Hive engine successfully bootstrapped with Hive 2.3.9 runtime.

**Comment by ymZhao1001** [comment]
thank u !! but i will not work ,same error info "TProtocolException: Missing version in readMessageBegin, old client"
