### ISSUE TITLE
[Improvement] Support to show more engine submission failure error for issue tracking 

### ISSUE THREAD

**Issue by Kwafoor** [apache/kyuubi#5304]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Current Kyuubi can recognize the exception information when starting the Engine and return the last Error. However, sometimes the last exception is not the root cause of the Engine start-up. Usually, we need multiple exceptions to determine the fundamental reason for the failure of the engine's launch. Is it possible to return the last several exceptions to better support issue tracking when the engine fails to start? This is an error log from a Spark engine start-up. Kyuubi recognized the exception but was unable to capture the fundamental cause of the engine's failure to start.
```
Caused by: java.lang.RuntimeException: org.apache.kyuubi.KyuubiSQLException:Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
 See more: /xxxxxxxxx/kyuubi-spark-sql-engine.log.52
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.engine.ProcBuilder.$anonfun$start$1(ProcBuilder.scala:142)
	... 1 more
```
The root cause log of failure is as follows:
```
23/09/18 09:21:57 INFO SparkContext: Successfully stopped SparkContext
23/09/18 09:21:57 ERROR SparkSQLEngine: Failed to instantiate SparkSession: requirement failed: initial executor number 501 must between min executor number 0 and max executor number 500
java.lang.IllegalArgumentException: requirement failed: initial executor number 501 must between min executor number 0 and max executor number 500
```

### How should we improve?

We could enhance our issue tracking process by defaulting to return multiple exceptions and including the appId in our log entries.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Specific to engine bootstrap, have you tried to use Kyuubi Beeline? It can retrieve all logs of the engine bootstrap.

**Comment by Kwafoor** [comment]
> Specific to engine bootstrap, have you tried to use Kyuubi Beeline? It can retrieve all logs during the engine bootstrap phase.

Is there any specific setting that needs to be added? Under default settings, the error reported is basically the same when I test the same failure reason using beeline.
```
Error opening session for xxx client ip xxxx, due to org.apache.kyuubi.KyuubiSQLException: Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
 See more: /xxxxxxx/kyuubi-spark-sql-engine.log.273 Retrying 0 of 1
```

**Comment by pan3793** [comment]
Emm, seems we are talking different things, I know what you mean now, and I agree with you that there is room to improve the error message extraction. But maybe we can improve the extracting rule rather than roughly extracting more stacktrace

**Comment by pan3793** [comment]
Maybe we can recognize and eliminate some helpless tailing stacktrace, the root cause could be exposed then.

**Comment by Kwafoor** [comment]
> Maybe we can recognize and eliminate some helpless tailing stacktrace, the root cause could be exposed then.

Eliminate helpless tailing stacktrace is a good idea, I will give it a try.
