### ISSUE TITLE
[TASK][Easy] Fix flaky test SessionsResourceSuite

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#5600]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- scala

### Background and Goals

```
SessionsResourceSuite:
- open/close and count session *** FAILED ***
  1 equaled 1, but 0 did not equal 1 (SessionsResourceSuite.scala:65)
- getSessionList *** FAILED ***
  List(Map("duration" -> 0, "sessionType" -> "INTERACTIVE", "identifier" -> "96ca05ee-ecb1-49cd-a2e4-66cbf49ed343", "createTime" -> 1698822938391, "ipAddr" -> "127.0.0.1", "exception" -> "", "kyuubiInstance" -> "localhost:35415", "idleTime" -> 78, "engineId" -> "", "conf" -> Map("kyuubi.session.real.user" -> "anonymous", "testConfig" -> "testValue", "kyuubi.client.ipAddress" -> "127.0.0.1", "kyuubi.session.connection.url" -> "localhost:35415", "kyuubi.server.ipAddress" -> "localhost"), "user" -> "anonymous")) was not empty (SessionsResourceSuite.scala:104)
```

### Implementation steps

fix these tests above that occasionally fail in CI

**Comment by davidyuan1223** [comment]
do you have this ci's complete log or url? i look the test code no problem, i need more info about the failed log

**Comment by yaooqinn** [comment]
Hi @davidyuan1223, my bad. I just remembered that I need to attach the link to the failed tests. I will update this ticket the next time I see the errors.

**Comment by yaooqinn** [comment]
https://github.com/apache/kyuubi/actions/runs/6781271541/job/18431279275?pr=5639

FYI, @davidyuan1223

**Comment by davidyuan1223** [comment]
> https://github.com/apache/kyuubi/actions/runs/6781271541/job/18431279275?pr=5639
> 
> FYI, @davidyuan1223

get, you can assigned me, i will try to fix this

**Comment by yaooqinn** [comment]
Thank you @davidyuan1223

**Comment by davidyuan1223** [comment]
find root case, actually the open session is always wrong, because we use thread, so if the test case execute quickly, the thread will not execute the error location the test case finished, but because the github ci maybe execute slowly, so we can get the failed.I need more time to find the error root cause, you can add Thread.sleepe(10000) like this picture,you will get the same error
![image](https://github.com/apache/kyuubi/assets/51512358/fdf3fcb1-34f4-4115-98b6-e7feefd38c91)

**Comment by yaooqinn** [comment]
It seems we can skip asserting activeCount

**Comment by davidyuan1223** [comment]
> It seems we can skip asserting activeCount

not find the root cause and fix?

**Comment by yaooqinn** [comment]
The open session step generates a background task, if you slept for a while, it made sure that the task was submitted.

Then it's not necessary for such an unpredictable assertion.

Or we can wrap it with `eventually(timeout) {}`

**Comment by davidyuan1223** [comment]
> The open session step generates a background task, if you slept for a while, it made sure that the task was submitted.
> 
> Then it's not necessary for such an unpredictable assertion.
> 
> Or we can wrap it with `eventually(timeout) {}`

```
org.apache.kyuubi.KyuubiSQLException: Illegal Operation state transition from CLOSED to FINISHED
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:70)
	at org.apache.kyuubi.operation.OperationState$.validateTransition(OperationState.scala:59)
	at org.apache.kyuubi.operation.AbstractOperation.setState(AbstractOperation.scala:112)
	at org.apache.kyuubi.operation.KyuubiOperation.setState(KyuubiOperation.scala:209)
	at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$2(LaunchEngine.scala:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
this is the test case's unit-test.log error log, could you test in local env and check the unit-test.log so that i can make sure it's a exception, not the thread complete quickly?
