### ISSUE TITLE
[Bug] kyuubi failed to read atlas.rest.address

### ISSUE THREAD

**Issue by SwordyZhao** [apache/kyuubi#5991]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

This error occurs when atlas.rest.address is configured with multiple addresses

### Affects Version(s)

1.8.0

### Kyuubi Engine Log Output

```logtalk
24/01/18 15:13:12 ERROR AtlasBaseClient: attempt #4: Service [http://bjbd-test-bigdata-atlas-002:21000 - could not get status
java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: [http://bjbd-test-bigdata-atlas-002:21000
        at java.net.URI.create(URI.java:852)
        at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:95)
        at org.apache.atlas.AtlasBaseClient.getAddressIfActive(AtlasBaseClient.java:613)
        at org.apache.atlas.AtlasBaseClient.selectActiveServerAddress(AtlasBaseClient.java:597)
        at org.apache.atlas.AtlasBaseClient.determineActiveServiceURL(AtlasBaseClient.java:323)
        at org.apache.atlas.AtlasBaseClient.initializeState(AtlasBaseClient.java:460)
        at org.apache.atlas.AtlasBaseClient.initializeState(AtlasBaseClient.java:448)
        at org.apache.atlas.AtlasBaseClient.<init>(AtlasBaseClient.java:131)
        at org.apache.atlas.AtlasClientV2.<init>(AtlasClientV2.java:139)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasRestClient.<init>(AtlasClient.scala:42)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasClient$.getClient(AtlasClient.scala:71)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasLineageDispatcher.$anonfun$send$2(AtlasLineageDispatcher.scala:37)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasLineageDispatcher.$anonfun$send$2$adapted(AtlasLineageDispatcher.scala:30)
        at scala.Option.foreach(Option.scala:407)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasLineageDispatcher.send(AtlasLineageDispatcher.scala:30)
        at org.apache.kyuubi.plugin.lineage.SparkOperationLineageQueryExecutionListener.$anonfun$onSuccess$1(SparkOperationLineageQueryExecutionListener.scala:35)
        at org.apache.kyuubi.plugin.lineage.SparkOperationLineageQueryExecutionListener.$anonfun$onSuccess$1$adapted(SparkOperationLineageQueryExecutionListener.scala:35)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.kyuubi.plugin.lineage.SparkOperationLineageQueryExecutionListener.onSuccess(SparkOperationLineageQueryExecutionListener.scala:35)
        at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:158)
        at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:128)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:128)
        at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:140)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1433)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: [http://bjbd-test-bigdata-atlas-002:21000
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.checkChar(URI.java:3031)
        at java.net.URI$Parser.parse(URI.java:3047)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 40 more
24/01/18 15:13:16 INFO YarnClientSchedulerBackend: Requesting to kill executor(s) 1
24/01/18 15:13:16 INFO YarnClientSchedulerBackend: Actual list of executor(s) to be killed is 1
24/01/18 15:13:16 INFO ExecutorAllocationManager: Executors 1 removed due to idle timeout.
24/01/18 15:13:17 INFO AtlasBaseClient: Trying with address  http://bjbd-test-bigdata-atlas-001:21000]
24/01/18 15:13:17 ERROR AtlasBaseClient: attempt #1: Service  http://bjbd-test-bigdata-atlas-001:21000] - could not get status
java.lang.IllegalArgumentException: Illegal character in scheme name at index 0:  http://bjbd-test-bigdata-atlas-001:21000]
        at java.net.URI.create(URI.java:852)
        at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:95)
        at org.apache.atlas.AtlasBaseClient.getAddressIfActive(AtlasBaseClient.java:613)
        at org.apache.atlas.AtlasBaseClient.selectActiveServerAddress(AtlasBaseClient.java:597)
        at org.apache.atlas.AtlasBaseClient.determineActiveServiceURL(AtlasBaseClient.java:323)
        at org.apache.atlas.AtlasBaseClient.initializeState(AtlasBaseClient.java:460)
        at org.apache.atlas.AtlasBaseClient.initializeState(AtlasBaseClient.java:448)
        at org.apache.atlas.AtlasBaseClient.<init>(AtlasBaseClient.java:131)
        at org.apache.atlas.AtlasClientV2.<init>(AtlasClientV2.java:139)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasRestClient.<init>(AtlasClient.scala:42)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasClient$.getClient(AtlasClient.scala:71)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasLineageDispatcher.$anonfun$send$2(AtlasLineageDispatcher.scala:37)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasLineageDispatcher.$anonfun$send$2$adapted(AtlasLineageDispatcher.scala:30)
        at scala.Option.foreach(Option.scala:407)
        at org.apache.kyuubi.plugin.lineage.dispatcher.atlas.AtlasLineageDispatcher.send(AtlasLineageDispatcher.scala:30)
        at org.apache.kyuubi.plugin.lineage.SparkOperationLineageQueryExecutionListener.$anonfun$onSuccess$1(SparkOperationLineageQueryExecutionListener.scala:35)
        at org.apache.kyuubi.plugin.lineage.SparkOperationLineageQueryExecutionListener.$anonfun$onSuccess$1$adapted(SparkOperationLineageQueryExecutionListener.scala:35)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.kyuubi.plugin.lineage.SparkOperationLineageQueryExecutionListener.onSuccess(SparkOperationLineageQueryExecutionListener.scala:35)
        at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:158)
        at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:128)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:128)
        at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:140)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1433)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0:  http://bjbd-test-bigdata-atlas-001:21000]
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.checkChar(URI.java:3031)
        at java.net.URI$Parser.parse(URI.java:3047)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 40 more
```

### Kyuubi Engine Configurations

```yaml
###atlas-application.properties
atlas.rest.address=http://bjbd-test-bigdata-atlas-002:21000,http://bjbd-test-bigdata-atlas-001:21000
```

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
cc @wForget

**Comment by SwordyZhao** [comment]
This error occurs because when the java class ApplicationProperties reads the configuration, configuration items with multiple values are returned as a java List. When kyuubi handles the configuration, it does not handle the java List specifically, so it calls the toString method, and the toString of java List returns a string with brackets, resulting in a configuration read error
