### ISSUE TITLE
[Improvement] Add some HttpClient options for EngineUIProxyServlet

### ISSUE THREAD

**Issue by minyk** [apache/kyuubi#6165]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

HttpClient of EngineUIProxyServlet has only 4k request buffer for default setting. So if there are too many headers, it cannot make a request with DEBUG message:
```
2024-03-07 11:23:57.401 KyuubiRestFrontendService-1637 DEBUG org.eclipse.jetty.client.HttpSender: Generated headers (4096 bytes), chunk (-1 bytes), content (0 bytes) - HEADER_OVERFLOW/HttpGenerator@48e4e170{s=START}
2024-03-07 11:23:57.401 KyuubiRestFrontendService-1637 DEBUG org.eclipse.jetty.client.HttpSender: Request failure HttpRequest[GET /jobs/ HTTP/1.1]@52519fe9
org.eclipse.jetty.http.BadMessageException: 500: Request header too large
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.process(HttpSenderOverHTTP.java:235) [jetty-client-9.4.52.v20230823.jar:9.4.52.v20230823]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:248) [jetty-util-9.4.52.v20230823.jar:9.4.52.v20230823]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:229) [jetty-util-9.4.52.v20230823.jar:9.4.52.v20230823]
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:65) [jetty-client-9.4.52.v20230823.jar:9.4.52.v20230823]
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:212) [jetty-client-9.4.52.v20230823.jar:9.4.52.v20230823]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:84) [jetty-client-9.4.52.v20230823.jar:9.4.52.v20230823]
```

Then return to 500 http status code to user.

### How should we improve?

Add some configs for HttpClient in EngineUIProxyServlet. These configs are used in here: https://eclipse.dev/jetty/javadoc/jetty-9/org/eclipse/jetty/proxy/AbstractProxyServlet.html#createHttpClient()

config | default | description
-- | -- | --
maxThreads | 256 | The max number of threads of HttpClient's Executor. If not set, or set to the value of "-", then the Jetty server thread pool will be used.
maxConnections | 32768 | The max number of connections per destination, see HttpClient.setMaxConnectionsPerDestination(int)
idleTimeout | 30000 | The idle timeout in milliseconds, see HttpClient.setIdleTimeout(long)
timeout | 60000 | The total timeout in milliseconds, see Request.timeout(long, java.util.concurrent.TimeUnit)
requestBufferSize | HttpClient's default | The request buffer size, see HttpClient.setRequestBufferSize(int)
responseBufferSize | HttpClient's default | The response buffer size, see HttpClient.setResponseBufferSize(int)

We can use `kyuubi.frontend.rest.jetty.engine-ui-proxy.httpclient` is the prefix of above configs.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
the proposal makes sense, how about using `kyuubi.frontend.rest.proxy.jetty.client.*` as the configuration prefix?

Regarding the configuration name policy, let us use a common namespace that is independent of the implementation (in this case, jetty), so the common part should be `kyuubi.frontend.rest.proxy.`, then `<impl>.<subnamespace>.<impl-key>`, e.g. 

```
kyuubi.frontend.rest.proxy.jetty.xxx
kyuubi.frontend.rest.proxy.tomcat.client.xxx
```

**Comment by minyk** [comment]
@pan3793 that makes sense. Thank you for your suggestion.
