### ISSUE TITLE
[TASK][TRIVIAL] Avoid NPE in MySQLErrPacket

### ISSUE THREAD

**Issue by wForget** [apache/kyuubi#6291]
### What's the level of this task?

TRIVIAL

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

+ Basic knowledge on scala

### Background and Goals

NullPointerException may occur in MySQLErrPacket

```
- transfer connection url when opening connection
java.lang.NullPointerException
	at org.apache.kyuubi.server.mysql.MySQLErrPacket$.apply(MySQLGenericPackets.scala:57)
	at org.apache.kyuubi.server.mysql.MySQLCommandHandler.exceptionCaught(MySQLCommandHandler.scala:63)
	at org.apache.kyuubi.server.mysql.MySQLCommandHandler.$anonfun$channelRead0$2(MySQLCommandHandler.scala:86)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### Implementation steps

Add non-null detection for `e.getMessage`

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by zhaohehuhu** [comment]
plz assign this task to me @wForget
