### ISSUE TITLE
[Bug] Close session fails in Flink engine

### ISSUE THREAD

**Issue by wForget** [apache/kyuubi#6352]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Close session fails in Flink engine.

### Affects Version(s)

1.8.0

### Kyuubi Engine Log Output

```logtalk
2024-04-28 18:46:20,249 WARN  org.apache.kyuubi.engine.flink.session.FlinkSQLSessionManager [] - Error checking session SessionHandle [122b9806-9feb-4625-845a-e305834714f5] timeout
java.lang.RuntimeException: Method closeSession(org.apache.flink.table.gateway.api.session.SessionHandle) not found in class org.apache.flink.table.gateway.service.session.SessionManagerImpl [checkSessionCount(), closeSession(org.apache.flink.table.gateway.api.session.SessionHandle), closeSession(org.apache.flink.table.gateway.service.session.Session), currentSessionCount(), equals(java.lang.Object), getClass(), getOperationCount(org.apache.flink.table.gateway.api.session.SessionHandle), getSession(org.apache.flink.table.gateway.api.session.SessionHandle), hashCode(), isSessionAlive(org.apache.flink.table.gateway.api.session.SessionHandle), isSessionExpired(org.apache.flink.table.gateway.service.session.Session), lambda$start$0(), notify(), notifyAll(), openSession(org.apache.flink.table.gateway.api.session.SessionEnvironment), start(), stop(), toString(), wait(), wait(long), wait(long, int)]
	at org.apache.kyuubi.util.reflect.ReflectUtils$.invokeAs(ReflectUtils.scala:103) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at org.apache.kyuubi.engine.flink.shim.FlinkSessionManager.closeSession(FlinkSessionManager.scala:57) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at org.apache.kyuubi.engine.flink.session.FlinkSQLSessionManager.$anonfun$closeSession$1(FlinkSQLSessionManager.scala:82) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at org.apache.kyuubi.engine.flink.session.FlinkSQLSessionManager.$anonfun$closeSession$1$adapted(FlinkSQLSessionManager.scala:81) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at scala.Option.foreach(Option.scala:257) ~[flink-scala_2.12-1.18.0.jar:1.18.0]
	at org.apache.kyuubi.engine.flink.session.FlinkSQLSessionManager.closeSession(FlinkSQLSessionManager.scala:81) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at org.apache.kyuubi.session.SessionManager$$anon$1.$anonfun$run$2(SessionManager.scala:315) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at org.apache.kyuubi.session.SessionManager$$anon$1.$anonfun$run$2$adapted(SessionManager.scala:309) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at scala.collection.Iterator.foreach(Iterator.scala:937) [flink-scala_2.12-1.18.0.jar:1.18.0]
	at scala.collection.Iterator.foreach$(Iterator.scala:937) [flink-scala_2.12-1.18.0.jar:1.18.0]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425) [flink-scala_2.12-1.18.0.jar:1.18.0]
	at scala.collection.IterableLike.foreach(IterableLike.scala:70) [flink-scala_2.12-1.18.0.jar:1.18.0]
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69) [flink-scala_2.12-1.18.0.jar:1.18.0]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) [flink-scala_2.12-1.18.0.jar:1.18.0]
	at org.apache.kyuubi.session.SessionManager$$anon$1.run(SessionManager.scala:309) [kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_382]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_382]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_382]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_382]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_382]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_382]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]
Caused by: java.lang.RuntimeException
	at org.apache.kyuubi.util.reflect.DynMethods$UnboundMethod.invoke(DynMethods.java:80) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at org.apache.kyuubi.util.reflect.DynMethods$BoundMethod.invoke(DynMethods.java:175) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	at org.apache.kyuubi.util.reflect.ReflectUtils$.invokeAs(ReflectUtils.scala:91) ~[kyuubi-flink-sql-engine_2.12-1.8.0.jar:1.8.0]
	... 21 more
```

### Additional context

Flink version: 1.18.0

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by wForget** [comment]
I guess this may be related to using different classloaders. After #6259, we deleted reflection call, I think this problem may not occur in master.
