### ISSUE TITLE
[Bug] spark historyserver Show incomplete applications kyuubi query engine ui error

### ISSUE THREAD

**Issue by felixzh2020** [apache/kyuubi#6476]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

spark historyserver Show incomplete applications kyuubi query engine ui error

```
<html>
<body>
<!--StartFragment--><h2 style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long</h2>
URI: | /history/application_1698577744226_0074/kyuubi/
-- | --
500
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
org.apache.spark.ui.JettyUtils$$anon$1-1fc4c49c
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at scala.runtime.BoxesRunTime.unboxToLong(BoxesRunTime.java:107)
	at org.apache.spark.ui.StatementStatsPagedTable.row(EnginePage.scala:542)
	at org.apache.spark.ui.StatementStatsPagedTable.row(EnginePage.scala:452)
	at org.apache.spark.ui.PagedTable.$anonfun$table$1(PagedTable.scala:127)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)</pre><!--EndFragment-->
</body>
</html>
```

### Affects Version(s)

master/1.9.1

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
What's your Spark app/history server version?

**Comment by felixzh2020** [comment]
3.3.2

**Comment by felixzh2020** [comment]
reproduce this problem：need to exec some sql.
[ApplicationMaster](http://felixzh1:8088/proxy/application_1698577744226_0077/) -> Kyuubi Query Engine is ok.
Spark historyserver Show incomplete applications -> Kyuubi Query Engine is error.

**Comment by wForget** [comment]
Looks like it's related to https://github.com/FasterXML/jackson-module-scala/issues/62

We can add `@JsonDeserialize(contentAs = classOf[java.lang.Long])` annotation to operationRunTime/operationCpuTime

**Comment by felixzh2020** [comment]
My modification method is effective in our product, but it doesn't look like it's better than yours.
 I will try again using your method

**Comment by felixzh2020** [comment]
@wForget It works. Please review.

**Comment by felixzh2020** [comment]
@wForget add ok.
