### ISSUE TITLE
[Bug] buildURI throw runtime exception

### ISSUE THREAD

**Issue by jeanlyn** [apache/kyuubi#6516]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When using pyspark on yarn cluster mode, and setting `kyuubi.engine.spark.python.home.archive` to hdfs paths, it throws the   exception like :

```
org.apache.kyuubi.KyuubiSQLException: Failed to init python environment, fall back to SQL mode: null
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.engine.spark.operation.SparkSQLOperationManager.newExecuteStatementOperation(SparkSQLOperationManager.scala:124)
        at org.apache.kyuubi.session.AbstractSession.$anonfun$executeStatement$1(AbstractSession.scala:130)
        at org.apache.kyuubi.session.AbstractSession.withAcquireRelease(AbstractSession.scala:82)
        at org.apache.kyuubi.session.AbstractSession.executeStatement(AbstractSession.scala:128)
        at org.apache.kyuubi.service.AbstractBackendService.executeStatement(AbstractBackendService.scala:66)
        at org.apache.kyuubi.service.TFrontendService.ExecuteStatement(TFrontendService.scala:253)
        at org.apache.kyuubi.shaded.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1670)
        at org.apache.kyuubi.shaded.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1650)
        at org.apache.kyuubi.shaded.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.kyuubi.shaded.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:35)
        at org.apache.kyuubi.shaded.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:250)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: null
        at org.apache.kyuubi.util.reflect.DynMethods$UnboundMethod.invoke(DynMethods.java:80)
        at org.apache.kyuubi.engine.spark.KyuubiSparkUtil$.buildURI(KyuubiSparkUtil.scala:143)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython$.$anonfun$getSparkPythonHomeFromArchive$1(ExecutePython.scala:319)
        at scala.Option.map(Option.scala:230)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython$.getSparkPythonHomeFromArchive(ExecutePython.scala:316)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython$.$anonfun$createSessionPythonWorker$5(ExecutePython.scala:280)
        at scala.collection.immutable.HashMap$HashMap1.getOrElse0(HashMap.scala:361)
        at scala.collection.immutable.HashMap$HashTrieMap.getOrElse0(HashMap.scala:594)
        at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:73)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython$.createSessionPythonWorker(ExecutePython.scala:280)
        at org.apache.kyuubi.engine.spark.operation.SparkSQLOperationManager.$anonfun$newExecuteStatementOperation$9(SparkSQLOperationManager.scala:119)
        at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
        at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
        at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:349)
        at org.apache.kyuubi.engine.spark.operation.SparkSQLOperationManager.newExecuteStatementOperation(SparkSQLOperationManager.scala:119)
```

### Affects Version(s)

1.9.1

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
My bad, seems `KyuubiSparkUtil#buildURI` is not covered by UT. The fix should be

```patch
  def buildURI(uri: URI, fragment: String): URI = {
    if (SPARK_ENGINE_RUNTIME_VERSION >= "4.0") {
      var uriBuilder = DynMethods.builder("fromUri")
        .impl("jakarta.ws.rs.core.UriBuilder", classOf[URI])
-       .build()
+       .buildStatic()
        .invoke[AnyRef](uri)
        
        ...
    } else {
      var uriBuilder = DynMethods.builder("fromUri")
        .impl("javax.ws.rs.core.UriBuilder", classOf[URI])
-       .build()
+       .buildStatic()
        .invoke[AnyRef](uri)

        ...
```

**Comment by jeanlyn** [comment]
Yes, I submit a pull request to fix this

> My bad, seems `KyuubiSparkUtil#buildURI` is not covered by UT. The fix should be
> 
> ```diff
>   def buildURI(uri: URI, fragment: String): URI = {
>     if (SPARK_ENGINE_RUNTIME_VERSION >= "4.0") {
>       var uriBuilder = DynMethods.builder("fromUri")
>         .impl("jakarta.ws.rs.core.UriBuilder", classOf[URI])
> -       .build()
> +       .buildStatic()
>         .invoke[AnyRef](uri)
>         
>         ...
>     } else {
>       var uriBuilder = DynMethods.builder("fromUri")
>         .impl("javax.ws.rs.core.UriBuilder", classOf[URI])
> -       .build()
> +       .buildStatic()
>         .invoke[AnyRef](uri)
> 
>         ...
> ```

Yes, and the invoke also need to modify. I submit a pr to fix this, could you take a look at it?
