### ISSUE TITLE
[Bug] checkEngineConnectionAlive may throw NPE

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6534]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

NPE occurs on launching Spark engine.

### Affects Version(s)

master/branch-1.9

### Kyuubi Server Log Output

```logtalk
java.lang.NullPointerException: Cannot invoke "org.apache.kyuubi.client.KyuubiSyncThriftClient.remoteEngineBroken()" because the return value of "org.apache.kyuubi.session.KyuubiSessionImpl.client()" is null
        at org.apache.kyuubi.session.KyuubiSessionImpl.checkEngineConnectionAlive(KyuubiSessionImpl.scala:321)
        at org.apache.kyuubi.session.KyuubiSessionManager.$anonfun$startEngineAliveChecker$2(KyuubiSessionManager.scala:421)
        at org.apache.kyuubi.session.KyuubiSessionManager.$anonfun$startEngineAliveChecker$2$adapted(KyuubiSessionManager.scala:418)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at org.apache.kyuubi.session.KyuubiSessionManager.$anonfun$startEngineAliveChecker$1(KyuubiSessionManager.scala:418)
        at org.apache.kyuubi.util.ThreadUtils$.$anonfun$scheduleTolerableRunnableWithFixedDelay$1(ThreadUtils.scala:126)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
caused by https://github.com/apache/kyuubi/pull/6468
