### ISSUE TITLE
[Bug] Running with paimon failed with class not found exception

### ISSUE THREAD

**Issue by AngersZhuuuu** [apache/kyuubi#6633]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
java.lang.NoClassDefFoundError: [Lorg/apache/spark/sql/connector/catalog/Column;
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at org.apache.kyuubi.plugin.spark.authz.util.AuthZUtils$.invoke(AuthZUtils.scala:63)
	at org.apache.kyuubi.plugin.spark.authz.util.AuthZUtils$.invokeAs(AuthZUtils.scala:77)
	at org.apache.kyuubi.plugin.spark.authz.serde.TableExtractor$.getOwner(tableExtractors.scala:52)
	at org.apache.kyuubi.plugin.spark.authz.serde.DataSourceV2RelationTableExtractor.$anonfun$apply$8(tableExtractors.scala:142)
	at scala.Option.flatMap(Option.scala:271)
	at org.apache.kyuubi.plugin.spark.authz.serde.DataSourceV2RelationTableExtractor.apply(tableExtractors.scala:140)
	at org.apache.kyuubi.plugin.spark.authz.serde.DataSourceV2RelationTableExtractor.apply(tableExtractors.scala:129)
	at org.apache.kyuubi.plugin.spark.authz.serde.ScanDesc.extract(Descriptor.scala:307)
	at org.apache.kyuubi.plugin.spark.authz.serde.ScanSpec.$anonfun$tables$2(CommandSpec.scala:102)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at org.apache.kyuubi.plugin.spark.authz.serde.ScanSpec.$anonfun$tables$1(CommandSpec.scala:100)
	at org.apache.kyuubi.plugin.spark.authz.ram.RamPrivilegesBuilder$.buildQuery(RamPrivilegesBuilder.scala:164)
```

Caused by paomin low version extension jar SparkTable will carry high version spark class

### Affects Version(s)

master, 1.8.0

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by wuhua08** [comment]
1.7.3也碰到了这问题

**Comment by monkeyboy123** [comment]
@AngersZhuuuu  How did you solve this problem? I've encountered the same issue.

**Comment by pan3793** [comment]
it's a paimon side issue - lower version of spark (3.3 and earlier) connector links classes introduced in spark 3.4. and kyuubi 1.13 drops the old version of spark and now requires spark 3.5+. in any of aspect, it's an invalid issue.

**Comment by monkeyboy123** [comment]
@pan3793  thanks 

> it's a paimon side issue - lower version of spark (3.3 and earlier) connector links classes introduced in spark 3.4. and kyuubi 1.13 drops the old version of spark and now requires spark 3.5+. in any of aspect, it's an invalid issue.
